# Generated by Django 3.1 on 2020-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('event_date', models.CharField(max_length=200)),
                ('event_image', models.FileField(max_length=200, upload_to='images/addevent/')),
            ],
        ),
    ]
