# Generated by Django 3.1 on 2020-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsite', '0002_addevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('package_image', models.FileField(max_length=200, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='addevent',
            name='event_image',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
