# Generated by Django 3.1 on 2020-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsite', '0005_addevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
