# Generated by Django 3.1 on 2020-08-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsite', '0009_auto_20200829_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpackage',
            name='package_image',
        ),
    ]
